name: job_circular_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  google_fonts: ^4.0.3
  intl: ^0.18.0
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  #for wishlist
  hive:
  hive_flutter:
  path_provider:
  firebase_auth:
  image_picker:
  firebase_storage:
  firebase_messaging:
  flutter_local_notifications:
  get_storage:
  file_picker:
  http:
  syncfusion_flutter_pdfviewer:
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  flutter_countdown_timer: ^4.1.0
  pinput: ^1.2.0
  flutter_datetime_picker: ^1.5.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
    ^2.0.0
    #for hive build model
  build_runner:
  hive_generator:
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/messenger.webp"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
